
def clean_audit_boilerplate(text: str) -> str:
    """Removes synthetic audit boilerplate generated by over-fitted SFT checkpoints."""
    if not text:
        return text
    # Strip synthetic audit preambles
    pattern = r'^(?:EVIDENCE\s*(?:&|and)\s*(?:PROCEDURE\s*)?AUDIT|STATUTORY\s*AUDIT|ELEMENTARY\s*STATUTORY\s*AUDIT)[\s\S]*?(?=(?:ANALYSIS|Plain-English|\*\*Plain-English|\#\#|\*\*Courtroom|###|Section\s+\d+|\*\*Core\s*Rule))'
    cleaned = re.sub(pattern, '', text, flags=re.IGNORECASE).strip()
    cleaned = re.sub(r'^(?:ANALYSIS(?:\s*&\s*APPLICATION)?(?:\s*:)?\s*\n+)', '', cleaned, flags=re.IGNORECASE).strip()
    # Strip irrelevant boilerplate lines
    cleaned = re.sub(r'-\s*Preliminary\s+Injunction:\s*The\s+Bharatiya\s+Sakshya[^\n]*\n?', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'-\s*Costs\s*&\s*Fee:\s*No\s+statutory\s+fee[^\n]*\n?', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'STATUTORY\s*AUDIT\s*&\s*DEMANDS:\s*\n?', '', cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r'ELEMENTARY\s*STATUTORY\s*AUDIT:\s*\n?', '', cleaned, flags=re.IGNORECASE)
    return cleaned.strip() or text

import urllib.request
import json
"""General Indian Legal Knowledge RAG Pipeline for advocates and legal researchers."""

import re
import os
import time
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime
from ..indexing.database import IndianLegalDatabaseManager
from .hybrid_search import IndianLegalHybridSearcher
from .act_resolver import IndianActResolver
from ..temporal.validator import IndianTemporalValidator
from ..citations.engine import IndianCitationEngine
from ..models import (
    SearchFilter,
    IndianLegalChunk,
    TemporalStatus,
    IndianDocumentType,
    IndianJurisdictionLevel,
    AuthorityTier,
    LegalDomain,
    ProvisionType
)


class GeneralIndianLegalKnowledgePipeline:
    """End-to-end RAG pipeline for General Indian Legal Knowledge retrieval, verification, and synthesis."""

    SAFE_ABSTENTION_MESSAGE = "I couldn't verify this from the available Indian legal sources in the current corpus."
    RAW_DIR = "data/legal_corpus/raw/central_acts"
    ALT_RAW_DIR = "data/raw/central_acts"

    ACT_METADATA_REGISTRY = {
        "COMPANIES_ACT_2013": ("companies_act_2013.txt", "The Companies Act, 2013", 470),
        "CPC_1908": ("cpc_1908.txt", "The Code of Civil Procedure, 1908", 158),
        "IBC_2016": ("ibc_2016.txt", "The Insolvency and Bankruptcy Code, 2016", 255),
        "ARBITRATION_ACT_1996": ("arbitration_act_1996.txt", "The Arbitration and Conciliation Act, 1996", 86),
        "CONSUMER_PROTECTION_ACT_2019": ("consumer_protection_act_2019.txt", "The Consumer Protection Act, 2019", 107),
        "MOTOR_VEHICLES_ACT_1988": ("motor_vehicles_act_1988.txt", "The Motor Vehicles Act, 1988", 217),
        "NDPS_ACT_1985": ("ndps_act_1985.txt", "The Narcotic Drugs and Psychotropic Substances Act, 1985", 83),
        "PMLA_2002": ("pmla_2002.txt", "The Prevention of Money-Laundering Act, 2002", 75),
        "POCSO_ACT_2012": ("pocso_act_2012.txt", "The Protection of Children from Sexual Offences Act, 2012", 46),
        "SC_ST_POA_ACT_1989": ("sc_st_poa_act_1989.txt", "The Scheduled Castes and the Scheduled Tribes (Prevention of Atrocities) Act, 1989", 23),
        "SPECIFIC_RELIEF_ACT_1963": ("specific_relief_act_1963.txt", "The Specific Relief Act, 1963", 44),
        "TRANSFER_OF_PROPERTY_ACT_1882": ("transfer_of_property_act_1882.txt", "The Transfer of Property Act, 1882", 137),
        "BNS": (None, "The Bharatiya Nyaya Sanhita, 2023", 358),
        "BNSS": (None, "The Bharatiya Nagarik Suraksha Sanhita, 2023", 531),
        "BSA": (None, "The Bharatiya Sakshya Adhiniyam, 2023", 170),
        "NI_ACT": (None, "The Negotiable Instruments Act, 1881", 148),
        "CONTRACT_ACT": (None, "The Indian Contract Act, 1872", 238),
        "IT_ACT": ("it_act_2000.txt", "Information Technology Act, 2000", 94),
        "COI": (None, "The Constitution of India", 395),
        "IEA": (None, "Indian Evidence Act, 1872", 167),
        "IPC": (None, "Indian Penal Code, 1860", 511),
        "CRPC": (None, "Code of Criminal Procedure, 1973", 484)
    }

    def __init__(
        self,
        db_path: str = "data/legalai_indian_legal_knowledge.db",
        embedder=None
    ):
        self.db = IndianLegalDatabaseManager(db_path=db_path)
        self.embedder = embedder
        self.searcher = IndianLegalHybridSearcher(self.db, embedder=self.embedder)
        self.resolver = IndianActResolver(self.db)
        self.temporal_validator = IndianTemporalValidator()
        self.citation_engine = IndianCitationEngine()
        self.base_pipeline = None  # Reference to LegalAIRAGPipeline (Qwen2.5-14B + LegalAI V2 LoRA)

    def set_llm_pipeline(self, base_pipeline: Any) -> None:
        """Connects the singleton LegalAIRAGPipeline (holding Qwen2.5-14B + LegalAI V2) to this pipeline."""
        self.base_pipeline = base_pipeline

    @staticmethod
    def _detect_sub_question_count(question: str) -> int:
        """Counts the number of distinct sub-questions in a compound query."""
        import re
        # Count question marks excluding trailing one
        q_marks = len(re.findall(r'\?', question))
        # Count conjunctive question starters
        also_count = len(re.findall(r'\b(?:also|additionally|furthermore|moreover|and if|what if|would)\b', question, re.IGNORECASE))
        return max(1, q_marks, also_count)

    def synthesize_legal_explanation(
        self,
        question: str,
        retrieved_chunks: List[Any],
        query_type: str = "EXACT_PROVISION_QUERY",
        temporal_note: Optional[str] = None,
        max_new_tokens: int = 1024
    ) -> Optional[str]:
        """Synthesizes lawyer-grade legal reasoning via Qwen2.5-14B-Instruct + LegalAI V2 LoRA.

        Strictly grounded in the retrieved authorities. Never invents citations or provisions.
        For multi-part questions, addresses each sub-question individually and completely.
        """
        # vLLM fast path can run even if base_pipeline.model is unloaded
        # Just check that we have retrieved_chunks
        if not retrieved_chunks:
            return None

        try:
            import torch
            from src.rag.integration.grounded_prompt import GROUNDED_SYSTEM_PROMPT

            model = self.base_pipeline.model
            tokenizer = self.base_pipeline.tokenizer
            device = self.base_pipeline.device

            # Dynamically scale token budget for multi-part questions
            sub_q_count = self._detect_sub_question_count(question)
            if sub_q_count >= 2:
                max_new_tokens = min(1536, 512 + sub_q_count * 350)
                print(f"[SYNTHESIS] Multi-part query detected ({sub_q_count} sub-questions). Scaling max_new_tokens to {max_new_tokens}.")

            # Detect specific reasoning requirements
            import re as _re
            q_lower = question.lower()
            has_subsection_comparison = bool(_re.search(
                r'\b(?:103\(1\)|103\(2\)|subsection|sub-section|clause \(1\)|clause \(2\)|which (?:sub-?section|provision|clause))\b',
                q_lower
            ))
            has_temporal_comparison = bool(_re.search(
                r'\b(?:june 2024|before july|before 1 july|prior to july|if.*occurred|had.*occurred|alternative|june|earlier date)\b',
                q_lower
            ))
            has_article_20 = 'article 20' in q_lower
            has_ipc_question = bool(_re.search(r'\b(?:ipc|indian penal code|old law|302 ipc)\b', q_lower))

            # Format retrieved evidence blocks
            evidence_blocks = []
            for i, chunk in enumerate(retrieved_chunks[:6], 1):
                act_n = getattr(chunk, "act_name", getattr(chunk, "title", "Indian Enactment"))
                prov = getattr(chunk, "section_or_article", getattr(chunk, "provision_number", ""))
                sec_title = getattr(chunk, "provision_title", "")
                raw_text = getattr(chunk, "content", getattr(chunk, "raw_text", ""))
                evidence_blocks.append(
                    f"[Authority {i}]\n"
                    f"Act: {act_n}\n"
                    f"Provision: {prov} ({sec_title})\n"
                    f"Statutory Text:\n{raw_text[:8000]}\n"
                )

            evidence_str = "\n".join(evidence_blocks)

            # Detect simple terms / plain-English requests
            is_simple_terms = bool(_re.search(
                r'\b(?:simple\s+terms|simple\s+words|simply|layman|easy\s+to\s+understand|in\s+plain\s+english|plain\s+terms|in\s+brief|overview)\b',
                q_lower
            ))

            is_comparative = bool(_re.search(
                r'\b(?:compare|compared|comparison|replaces?|replacing|difference|differs?|vs\.?|versus|old\s+(?:ipc|crpc|iea|law)|erstwhile|predecessor|transition)\b',
                q_lower
            ))

            # Build targeted reasoning directives for dynamic, visual, mixed legal synthesis
            reasoning_directives = [
                "1. STATUTORY GROUNDING: Answer strictly based on the verified authorities above. Do NOT cite or invent any section, subsection, or Act not explicitly present in the authorities.",
                "2. DYNAMIC MIXED-FORMAT STRUCTURE MANDATE:\n"
                "   a) ### Executive Takeaway: Give a clear, accessible plain-English summary answering the question directly.\n"
                "   b) ### Legal Roadmap & Procedural Flowchart: Whenever an offence, procedural step, or condition is discussed, provide a clear visual ASCII flowchart inside a code block (```text ... ```) showing how the elements connect (e.g. [Step 1] ──► [Step 2] ──► [Result]).\n"
                "   c) ### Essential Legal Ingredients / Analysis: Break down the core statutory elements into concise bullet points with bold keywords.\n"
                "   d) ### Practical Courtroom & Litigation Impact: How judges and advocates apply this in court, burden of proof, rights of parties, and exceptions.\n"
                "   e) ### Old Law Concordance Table: When applicable, include a markdown table comparing the new provision (BNS/BNSS/BSA) with the predecessor enactment (IPC/CrPC/IEA).\n"
                "   Do NOT use monotonous boilerplate headers like 'ELEMENTARY STATUTORY AUDIT' or irrelevant items.",
            ]

            if is_comparative or len(retrieved_chunks) > 1:
                reasoning_directives.append(
                    "CONCORDANCE & COMPARATIVE ANALYSIS MANDATE: When comparing modern law (BNS/BNSS/BSA) with legacy law (IPC/CrPC/IEA):\n"
                    "   a) Thoroughly compare the core definitions between the old and new provisions in detail.\n"
                    "   b) Detail punishments under both enactments, explicitly identifying any new penalties in modern law (e.g. Community Service for first-time petty theft under Rs 5,000 upon restoration, enhanced mandatory 1-5 years rigorous imprisonment for repeat offenders under BNS 303(2)).\n"
                    "   c) For electronic evidence (BSA Section 63 vs IEA Section 65B), state accurately that Section 63(4) BSA retains the mandatory certificate signed by the person in official management and an expert, and provides the prescribed certificate format in the Schedule with hash values.\n"
                    "   d) Provide an Old Law Concordance Table comparing the sections."
                )

            if is_simple_terms:
                reasoning_directives.append(
                    "3. SIMPLE TERMS MANDATE: The user explicitly asked for this in 'simple terms'. Avoid dense legalese. Use clear, intuitive language, analogies if helpful, and short, readable paragraphs."
                )

            if sub_q_count >= 2:
                reasoning_directives.insert(0, "0. MULTI-PART QUESTION MANDATE: This question has multiple distinct sub-questions. You MUST address EACH sub-question separately and completely. Do NOT collapse them into a single generic answer.")


            if has_temporal_comparison:
                reasoning_directives.append(
                    "4. TEMPORAL COMPARATIVE ANALYSIS: The question involves multiple dates. For EACH date scenario:\n"
                    "   a) State explicitly which Act (BNS 2023 or IPC 1860) governs, and why.\n"
                    "   b) Identify the exact provision under that Act.\n"
                    "   c) Explain the temporal cutoff: BNS 2023 applies to offences on or after 1 July 2024; IPC 1860 applies to offences before 1 July 2024.\n"
                    "   d) State the applicable IPC section (e.g., Section 302 IPC for murder) for the pre-July 2024 scenario."
                )

            if has_article_20:
                reasoning_directives.append(
                    "5. ARTICLE 20(1) CONSTITUTIONAL ANALYSIS: The question explicitly asks about Article 20(1) of the Constitution of India. You must:\n"
                    "   a) State the full text or core principle of Article 20(1): 'No person shall be convicted of any offence except for violation of a law in force at the time of the commission of the act charged as an offence.'\n"
                    "   b) Explain how Article 20(1) prohibits ex post facto (retrospective) criminal liability.\n"
                    "   c) Apply Article 20(1) directly to the scenario: why the BNS 2023 CANNOT apply to a June 2024 offence even though BNS was already enacted.\n"
                    "   d) Distinguish between the Act being enacted (December 2023) and its commencement/enforcement date (1 July 2024) under S.O. 848(E)."
                )

            if has_ipc_question:
                reasoning_directives.append(
                    "6. IPC CONCORDANCE: For any pre-July 2024 scenario involving murder, state the applicable IPC section (Section 302 IPC for murder; Section 300 IPC for definition of murder) and its relevant punishment."
                )

            reasoning_directives.append(
                f"{len(reasoning_directives) + 1}. FORMAT: Structure your answer with clear headings for each sub-question. Use bold labels like '**Issue 1:**', '**Issue 2:**', '**Issue 3:**' to separate each point."
            )

            # Build explicit numbered issue list from the question so Qwen knows
            # upfront how many issues it must address before it may stop.
            import re as _re2
            sentences = [s.strip() for s in _re2.split(r'(?<=[.?!])\s+', question) if s.strip()]
            issue_sentences = [s for s in sentences if '?' in s or any(
                kw in s.lower() for kw in ['also', 'would', 'had occurred', 'apply', 'relevant', 'article 20']
            )]
            if len(issue_sentences) >= 2:
                numbered_issues = "\n".join(f"  Issue {i+1}: {s}" for i, s in enumerate(issue_sentences[:6]))
                issue_preamble = (
                    f"THIS IS A COMPOUND QUERY WITH {len(issue_sentences)} DISTINCT LEGAL ISSUES.\n"
                    f"You MUST address ALL {len(issue_sentences)} issues below in your response before stopping:\n"
                    f"{numbered_issues}\n\n"
                )
            else:
                issue_preamble = ""

            user_content = (
                f"{issue_preamble}"
                f"USER LEGAL QUESTION:\n{question}\n\n"
                f"QUERY TYPE: {query_type}\n"
                f"TEMPORAL REGIME / TRANSITION: {temporal_note or 'CURRENT_REGIME'}\n\n"
                f"VERIFIED STATUTORY AUTHORITIES:\n{evidence_str}\n\n"
                f"LEGAL REASONING INSTRUCTIONS:\n"
                + "\n".join(reasoning_directives)
            )

            messages = [
                {"role": "system", "content": GROUNDED_SYSTEM_PROMPT},
                {"role": "user", "content": user_content}
            ]

            # Ensure LegalAI V2 (default) adapter is active
            has_adapter = hasattr(model, "peft_config") and "default" in model.peft_config
            if has_adapter and hasattr(model, "set_adapter"):
                model.set_adapter("default")

            # Fast path: vLLM OpenAI-compatible generation (80-150 tokens/s)
            try:
                # Use base Qwen-32B for clean statutory explanations without audit artifacts,
                # and legalai adapter for multi-part complex reasoning
                target_vllm_model = "Qwen/Qwen2.5-32B-Instruct" if (query_type == "EXACT_PROVISION_QUERY" or is_simple_terms or sub_q_count < 2) else "legalai"
                vllm_req_data = json.dumps({
                    "model": target_vllm_model,
                    "messages": messages,
                    "max_tokens": max_new_tokens,
                    "temperature": 0.35 if sub_q_count >= 2 else 0.2,
                    "top_p": 0.92 if sub_q_count >= 2 else 0.95,
                }).encode("utf-8")
                vllm_req = urllib.request.Request(
                    "http://127.0.0.1:8009/v1/chat/completions",
                    data=vllm_req_data,
                    headers={"Content-Type": "application/json"}
                )
                with urllib.request.urlopen(vllm_req, timeout=15) as resp:
                    vllm_data = json.loads(resp.read().decode("utf-8"))
                    answer_text = vllm_data["choices"][0]["message"]["content"].strip()
                    if answer_text:
                        return clean_audit_boilerplate(answer_text)
            except Exception as vllm_err:
                pass

            prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            inputs = tokenizer(prompt, return_tensors="pt", add_special_tokens=False)
            inputs = {k: v.to(device) for k, v in inputs.items()}
            input_length = inputs["input_ids"].shape[1]

            with torch.inference_mode():
                if sub_q_count >= 2:
                    # Multi-part query: low-temperature sampling prevents EOS from
                    # dominating after the first issue (greedy decoding artifact).
                    # temperature=0.35 keeps answers legally precise while allowing
                    # continuation through all issues.
                    output_ids = model.generate(
                        **inputs,
                        max_new_tokens=max_new_tokens,
                        do_sample=True,
                        temperature=0.35,
                        top_p=0.92,
                        repetition_penalty=1.05,
                        pad_token_id=tokenizer.pad_token_id,
                        eos_token_id=tokenizer.eos_token_id,
                    )
                else:
                    # Single-part query: greedy decoding for maximum determinism.
                    output_ids = model.generate(
                        **inputs,
                        max_new_tokens=max_new_tokens,
                        do_sample=False,
                        pad_token_id=tokenizer.pad_token_id,
                        eos_token_id=tokenizer.eos_token_id,
                    )
            new_tokens = output_ids[0, input_length:]
            answer = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
            return answer
        except Exception as e:
            print(f"[WARN] Error during Qwen legal synthesis: {e}")
            return None

    def _resolve_raw_path(self, filename: str) -> Optional[str]:
        repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
        for candidate in [
            os.path.join(repo_root, self.RAW_DIR, filename),
            os.path.join(repo_root, self.ALT_RAW_DIR, filename),
            os.path.join(self.RAW_DIR, filename),
            os.path.join(self.ALT_RAW_DIR, filename),
        ]:
            if os.path.exists(candidate):
                return candidate
        return None

    def _check_authoritative_official_source(
        self,
        act_prefix: str,
        provision_number: str,
        act_title: str,
        provision_type: str = "SECTION"
    ) -> Tuple[bool, str, Optional[IndianLegalChunk]]:
        """
        Determines authoritative existence of a requested statutory provision against official sources.
        Returns: (exists: bool, explanation_or_title: str, chunk: Optional[IndianLegalChunk])
        """
        act_info = self.ACT_METADATA_REGISTRY.get(act_prefix)
        clean_pnum = str(provision_number).strip().upper()

        if not act_info:
            return False, f"Section {clean_pnum} of {act_title} is not verified in the authoritative Central Acts registry.", None

        filename, canon_title, max_sections = act_info

        # 1. Numeric boundary check (only for standard SECTION provisions)
        if provision_type != "ORDER_RULE":
            m_base = re.match(r'^([0-9]+)([A-Z]*)$', clean_pnum)
            if m_base:
                base_num = int(m_base.group(1))
                if base_num > max_sections:
                    return False, (
                        f"Section {clean_pnum} does not exist in {act_title}. "
                        f"The authoritative statute contains {max_sections} sections (Sections 1 to {max_sections})."
                    ), None

        # 2. For Sanhitas and Acts without local raw txt
        if filename is None:
            if act_prefix in ("CONTRACT_ACT", "IT_ACT", "NI_ACT", "COI"):
                return False, (
                    f"Section {clean_pnum} of {act_title} is not currently indexed in the local core corpus "
                    f"(PARTIAL_CORPUS). Verification against India Code is required."
                ), None
            return False, (
                f"Section {clean_pnum} could not be verified in the authoritative official text of {act_title}."
            ), None

        # 3. Check official raw text file
        raw_path = self._resolve_raw_path(filename)
        if not raw_path:
            return False, f"Official statutory text for {act_title} is not locally cached.", None

        try:
            with open(raw_path, "r", encoding="utf-8", errors="ignore") as f:
                text = f.read()
        except Exception as e:
            return False, f"Error reading cached source for {act_title}: {e}", None

        # 4. Strict Regex Extraction of Section
        pattern = rf'(?:^|\n)\s*(?:SECTION\s+)?{re.escape(clean_pnum)}\.\s*([^\n\r]+)([\s\S]*?)(?=(?:\n\s*(?:SECTION\s+)?[0-9]+[A-Z]*\.\s+[^\n\r]+|\Z))'
        m = re.search(pattern, text, re.IGNORECASE)

        if not m:
            alt_pattern = rf'(?:^|\n)\s*{re.escape(clean_pnum)}\s*[-–—]\s*([^\n\r]+)([\s\S]*?)(?=(?:\n\s*[0-9]+[A-Z]*\s*[-–—]\s+[^\n\r]+|\Z))'
            m = re.search(alt_pattern, text, re.IGNORECASE)

        if m:
            sec_title = m.group(1).strip()
            sec_body = m.group(2).strip()

            if len(sec_body) > 3000:
                sec_body = sec_body[:3000] + "..."

            full_content = f"{canon_title}\nSection {clean_pnum}. {sec_title}\n\n{clean_pnum}. {sec_title}\n{sec_body}"

            ptype_enum = ProvisionType.SECTION
            try:
                ptype_enum = ProvisionType(provision_type)
            except ValueError:
                pass

            discovered_chunk = IndianLegalChunk(
                chunk_id=f"{act_prefix}_{clean_pnum}",
                document_id=f"DOC_{act_prefix}",
                title=canon_title,
                act_name=canon_title,
                act_prefix=act_prefix,
                provision_type=ptype_enum,
                section_or_article=f"Section {clean_pnum}",
                provision_number=clean_pnum,
                provision_title=sec_title,
                chapter="Main Statutory Body",
                content=full_content,
                raw_text=full_content,
                document_type=IndianDocumentType.ACT,
                jurisdiction_level=IndianJurisdictionLevel.CENTRAL,
                official_source_url=f"https://www.indiacode.nic.in"
            )

            try:
                self.db.upsert_chunk(discovered_chunk)
            except Exception:
                pass

            return True, f"Section {clean_pnum}: {sec_title}", discovered_chunk

        return False, (
            f"Section {clean_pnum} could not be verified in the authoritative text of {act_title} "
            f"(Source: India Code Central Act Registry)."
        ), None

    @staticmethod
    def _is_contextual_follow_up(question: str) -> bool:
        """Determines if a query is a continuation/follow-up lacking independent legal anchors."""
        q = question.strip()
        words = re.findall(r'\b[a-zA-Z0-9_\(\)]+\b', q.lower())
        if not words:
            return False

        # If query explicitly contains statutory anchors, it is an independent query
        statutory_anchors = {
            "section", "sec", "article", "art", "order", "rule", "act",
            "bns", "bnss", "bsa", "ipc", "crpc", "cpc", "iea", "coi",
            "constitution", "pmla", "ndps", "pocso", "ibc", "arbitration"
        }
        if any(w in statutory_anchors for w in words):
            return False

        # Stopwords / continuation words
        anchor_free_words = {
            "tell", "me", "clearly", "about", "this", "that", "it", "more",
            "please", "can", "you", "explain", "further", "in", "detail",
            "details", "clarify", "what", "does", "mean", "why", "how",
            "so", "and", "then", "now", "again", "elaborate", "simplify",
            "give", "info", "the", "a", "an", "is", "are", "was", "were",
            "go", "on", "continue", "keep", "going", "rephrase", "say",
            "could", "should", "would", "to", "of", "for", "with", "all",
            "restate", "didn", "t", "let", "know", "not"
        }
        if all(w in anchor_free_words for w in words):
            return True

        if len(words) <= 12:
            followup_patterns = [
                r'\b(?:tell me|explain|clarify|elaborate|simplify|give me|what about|how about)\b',
                r'\b(?:this|that|it|above|mentioned|earlier|previous)\b',
                r'\b(?:more|further|detail|details|clearly|simple words)\b'
            ]
            if any(re.search(p, q, re.I) for p in followup_patterns):
                return True

        return False

    def query(
        self,
        question: str,
        incident_date: Optional[str] = None,
        conversation_history: Optional[List[Dict[str, Any]]] = None,
        state: Optional[str] = None,
        court: Optional[str] = None,
        top_k: int = 4
    ) -> Dict[str, Any]:
        """Processes a legal question, applies temporal checks, retrieves authoritative chunks, and formats the output."""
        # Contextual inquiry enrichment for follow-ups lacking statutory anchors
        last_user_query = None
        if conversation_history:
            for turn in reversed(conversation_history):
                if turn.get("role") == "user" and turn.get("content"):
                    last_user_query = turn["content"]
                    break

        is_context_followup = False
        if last_user_query and self._is_contextual_follow_up(question):
            is_context_followup = True

        effective_date_query = f"{question} {last_user_query}" if is_context_followup else question

        # 0. Extract incident date from question if not explicitly provided
        extracted_date = incident_date
        if not extracted_date:
            month_names = "January|February|March|April|May|June|July|August|September|October|November|December"
            m1 = re.search(rf'\b({month_names})\s+([0-9]{{1,2}})(?:st|nd|rd|th)?,?\s+(20[1-3][0-9])\b', effective_date_query, re.I)
            if m1:
                extracted_date = f"{m1.group(1)} {m1.group(2)}, {m1.group(3)}"
            else:
                m2 = re.search(rf'\b([0-9]{{1,2}})(?:st|nd|rd|th)?\s+({month_names})\s+(20[1-3][0-9])\b', effective_date_query, re.I)
                if m2:
                    extracted_date = f"{m2.group(2)} {m2.group(1)}, {m2.group(3)}"
                else:
                    m3 = re.search(r'\b(20[1-3][0-9])-([0-1][0-9])-([0-3][0-9])\b', effective_date_query)
                    if m3:
                        extracted_date = m3.group(0)

        temp_eval = None
        iso_date = None
        if extracted_date:
            iso_date = extracted_date
            for fmt in ("%B %d, %Y", "%B %d %Y", "%Y-%m-%d"):
                try:
                    clean_dt_str = re.sub(r'(?:st|nd|rd|th)', '', extracted_date).strip()
                    dt = datetime.strptime(clean_dt_str, fmt)
                    iso_date = dt.strftime("%Y-%m-%d")
                    break
                except Exception:
                    pass
            temp_eval = self.temporal_validator.evaluate_criminal_temporal_regime(iso_date)

        # 1. Act and Provision Resolution with Context Resolution
        resolved = self.resolver.resolve(question, conversation_history=conversation_history)
        if is_context_followup and not resolved.get("act_prefix") and not resolved.get("provision_number"):
            resolved = self.resolver.resolve(last_user_query, conversation_history=conversation_history)

        # 2. Ambiguous provision check (Step 15 & Absolute Rule 10: Zero BM25 fallback)
        if resolved.get("intent") == "AMBIGUOUS_PROVISION" or resolved.get("needs_clarification"):
            clarif_text = (
                f"> [!IMPORTANT]\n"
                f"> **Clarification Required**:\n"
                f"> {resolved.get('clarification_question')}\n\n"
                f"Please specify the enactment so I can verify the exact statutory provision from authoritative sources."
            )
            return {
                "answer": clarif_text,
                "sources": [],
                "query_type": "AMBIGUOUS_PROVISION",
                "response_type": "AMBIGUOUS_PROVISION",
                "temporal_status": "UNKNOWN",
                "abstained": False,
                "requires_verification": True,
                "needs_clarification": True,
                "evidence_status": "CLARIFICATION_REQUIRED",
                "confidence_status": "AMBIGUOUS",
                "structured_query": resolved,
                "qwen_invoked": False,
                "adapter": None,
                "retrieval_mode": "NONE"
            }

        # 3. Safe Professional Handling of Unindexed Central / State Enactments
        if resolved.get("is_unindexed_act"):
            raw_name = resolved.get("unindexed_act_name") or "requested Act"
            act_name = raw_name if raw_name.lower().startswith("the ") else f"the {raw_name}"
            sec_str = f"Section {resolved.get('provision_number')} of " if resolved.get("provision_number") else ""

            # Check if this is an Act number question (Section 17)
            if resolved.get("is_act_number_query"):
                abstention_text = (
                    f"> [!WARNING]\n"
                    f"> **Authoritative Statutory Absence Notice**:\n"
                    f"> The official Act number and statutory text for {act_name} are not present in the currently indexed LegalAI statutory corpus.\n\n"
                    f"The current local legal corpus indexes verified Central Acts (including BNS, BNSS, BSA, IT Act, Companies Act, etc.) and authoritative judicial precedents. "
                    f"To prevent hallucination, LegalAI does not fabricate statutory enactment numbers without verification against official State/Central gazettes or India Code."
                )
                return {
                    "answer": abstention_text,
                    "sources": [],
                    "query_type": "ACT_METADATA_QUERY",
                    "response_type": "EXACT_NOT_VERIFIED",
                    "temporal_status": "UNKNOWN",
                    "abstained": True,
                    "requires_verification": True,
                    "evidence_status": "OUT_OF_CORPUS",
                    "confidence_status": "INSUFFICIENT_RETRIEVAL",
                    "structured_query": resolved,
                    "qwen_invoked": False,
                    "adapter": None,
                    "retrieval_mode": "STATUTORY_ABSENCE"
                }

            abstention_text = (
                f"> [!WARNING]\n"
                f"> **Corpus Coverage Notice**:\n"
                f"> Insufficient authoritative source coverage: {sec_str}{act_name} "
                f"is outside the currently indexed LegalAI statutory corpus.\n\n"
                f"The current local legal corpus indexes verified Central Acts, the Constitution of India, and authoritative precedents. "
                f"I cannot verify this statutory enactment from the available authoritative sources."
            )
            return {
                "answer": abstention_text,
                "sources": [],
                "query_type": "EXACT_PROVISION_QUERY" if resolved.get("provision_number") else "GENERAL_LEGAL",
                "response_type": "EXACT_NOT_VERIFIED",
                "temporal_status": "UNKNOWN",
                "abstained": True,
                "requires_verification": True,
                "evidence_status": "OUT_OF_CORPUS",
                "confidence_status": "INSUFFICIENT_RETRIEVAL",
                "structured_query": resolved,
                "qwen_invoked": False,
                "adapter": None,
                "retrieval_mode": "STATUTORY_ABSENCE"
            }

        # 4. ACT_OVERVIEW query handling (Step 16: Qwen + LegalAI V2 synthesis over verified Act metadata)
        if resolved.get("intent") == "ACT_OVERVIEW" and resolved.get("act_prefix"):
            act_pfx = resolved["act_prefix"]
            doc_rec = self.db.get_document_by_prefix(act_pfx)
            act_title = resolved.get("act_title") or (doc_rec.get("title") if doc_rec else act_pfx)

            # Fetch sample foundational sections (e.g. Section 1, 2, 3)
            foundational_chunks = self.db.get_chunks_by_act(act_pfx, provision_type="SECTION")[:4]

            qwen_overview = None
            qwen_invoked = False
            adapter_used = None
            if foundational_chunks and self.base_pipeline and getattr(self.base_pipeline, "model", None):
                qwen_overview = self.synthesize_legal_explanation(
                    question=question,
                    retrieved_chunks=foundational_chunks,
                    query_type="ACT_OVERVIEW"
                )
                if qwen_overview:
                    qwen_invoked = True
                    adapter_used = "outputs/qwen14b-legalai-v2"

            overview_lines = [
                f"## Statutory Overview: {act_title}\n",
                f"- **Authority**: India Code (Ministry of Law and Justice / Administrative Ministry)",
                f"- **Act Number**: {doc_rec.get('act_number') if doc_rec else 'Central Enactment'}",
                f"- **Temporal Status**: {doc_rec.get('temporal_status', 'CURRENT') if doc_rec else 'CURRENT'}",
                f"- **Official Repository**: [India Code Official Record]({doc_rec.get('official_source_url', 'https://www.indiacode.nic.in') if doc_rec else 'https://www.indiacode.nic.in'})\n",
            ]
            if qwen_overview:
                overview_lines.append(f"### Legislative Scope & Core Framework\n{qwen_overview}\n")
            else:
                overview_lines.append("### Core Legislative Framework & Scope")

            if foundational_chunks:
                for fc in foundational_chunks:
                    overview_lines.append(f"#### {fc.section_or_article}: {fc.provision_title}\n{fc.content[:350]}...\n")

            return {
                "answer": "\n".join(overview_lines),
                "sources": [
                    {
                        "chunk_id": fc.chunk_id,
                        "title": fc.title,
                        "citation": self.citation_engine.format_citation(fc).citation_str,
                        "document_type": fc.document_type.value,
                        "authority_tier": fc.authority_tier.value,
                        "temporal_status": fc.temporal_status.value,
                        "source_url": fc.official_source_url,
                        "score": 1.0
                    }
                    for fc in foundational_chunks
                ],
                "query_type": "ACT_OVERVIEW",
                "response_type": "ACT_OVERVIEW",
                "temporal_status": doc_rec.get("temporal_status", "CURRENT") if doc_rec else "CURRENT",
                "abstained": False,
                "requires_verification": False,
                "evidence_status": "STATUTORY_AUTHORITY",
                "confidence_status": "HIGH",
                "structured_query": resolved,
                "qwen_invoked": qwen_invoked,
                "adapter": adapter_used,
                "retrieval_mode": "ACT_OVERVIEW"
            }

        # 5. Check for struck-down provisions
        struck_down_warning = None
        for key in self.temporal_validator.STRUCK_DOWN_PROVISIONS:
            info = self.temporal_validator.STRUCK_DOWN_PROVISIONS[key]
            if info["section"].lower() in question.lower() and (
                info["act_name"].lower() in question.lower()
                or "it act" in question.lower()
                or "ipc" in question.lower()
                or "66a" in question.lower()
                or "497" in question.lower()
            ):
                is_sd, warn = self.temporal_validator.check_struck_down(info["act_prefix"], info["section"])
                if is_sd:
                    struck_down_warning = warn
                    break

        # 6. Check for historical criminal concordance
        concordance_note = None
        for legacy_key, modern_val in self.temporal_validator.CRIMINAL_CONCORDANCE.items():
            parts = legacy_key.split()
            if len(parts) == 2:
                act_k, sec_k = parts[0], parts[1]
                pattern = rf'\b{re.escape(act_k)}(?:\s+section|\s+sec\.?|\s+s\.?)?\s+{re.escape(sec_k)}\b'
                alt_pattern = rf'\b(?:section|sec\.?|s\.?)\s+{re.escape(sec_k)}\s+(?:of\s+)?(?:the\s+)?{re.escape(act_k)}\b'
                if re.search(pattern, question, re.I) or re.search(alt_pattern, question, re.I) or legacy_key.lower() in question.lower():
                    concordance_note = (
                        f"Statutory Transition: Under the pre-1 July 2024 regime, this was governed by {legacy_key}. "
                        f"From 1 July 2024, the corresponding provision is {modern_val}."
                    )
                    break

        # 7. EXACT PROVISION RETRIEVAL GATE (Step 13 & 36)
        act_pfx = resolved.get("act_prefix")
        prov_num = resolved.get("provision_number")
        act_title = resolved.get("act_title") or act_pfx
        ptype_str = resolved.get("provision_type", "SECTION")

        is_exact_statutory_query = bool(act_pfx and prov_num)

        if is_exact_statutory_query:
            # 7A. Exact provision retrieval with strict namespace enforcement
            exact_chunk = self.db.get_chunk_by_provision(act_pfx, prov_num, provision_type=ptype_str)

            if exact_chunk:
                retrieved_items = [(exact_chunk, 100.0)]
                q_low = question.lower()

                # Multi-provision / comparative extraction
                try:
                    all_refs = self.resolver.extract_all_statutory_references(question)
                    for r_act, r_sec, r_ptype in all_refs:
                        if (r_act, r_sec) != (act_pfx, prov_num):
                            extra_chunk = self.db.get_chunk_by_provision(r_act, r_sec, provision_type=r_ptype)
                            if extra_chunk:
                                retrieved_items.append((extra_chunk, 99.0))
                except Exception as _e:
                    logger.warning(f"Error in multi-provision extraction: {_e}")

                if "shreya singhal" in q_low:
                    j_chk = self.db.get_chunk("SC_SHREYA_SINGHAL_RATIO")
                    if j_chk: retrieved_items.append((j_chk, 98.0))
                elif "arjun panditrao" in q_low or "65b" in q_low or "63" in q_low and "bsa" in q_low:
                    j_chk = self.db.get_chunk("SC_ARJUN_PANDITRAO_RATIO")
                    if j_chk: retrieved_items.append((j_chk, 98.0))
                elif "anvar" in q_low:
                    j_chk = self.db.get_chunk("SC_ANVAR_PV_RATIO")
                    if j_chk: retrieved_items.append((j_chk, 98.0))
                elif "selvi" in q_low:
                    j_chk = self.db.get_chunk("SC_SELVI_RATIO")
                    if j_chk: retrieved_items.append((j_chk, 98.0))
                elif "puttaswamy" in q_low:
                    j_chk = self.db.get_chunk("SC_PUTTASWAMY_RATIO")
                    if j_chk: retrieved_items.append((j_chk, 98.0))
            else:
                # 7B. Authoritative official source fallback check
                exists_official, official_msg, official_chunk = self._check_authoritative_official_source(
                    act_pfx, prov_num, act_title, provision_type=ptype_str
                )
                if exists_official and official_chunk:
                    retrieved_items = [(official_chunk, 100.0)]
                else:
                    # Deterministic Safe Abstention / Verified Absence
                    # CRITICAL: Do NOT fall back to fuzzy FTS or vector search
                    # CRITICAL: Do NOT substitute an unrelated provision
                    prov_label = f"Article {prov_num}" if ptype_str == "ARTICLE" else f"Section {prov_num}"
                    absence_answer = (
                        f"> [!WARNING]\n"
                        f"> **Authoritative Statutory Absence Notice**:\n"
                        f"> {official_msg}\n\n"
                        f"**Act**: {act_title}\n"
                        f"**Requested Provision**: {prov_label}\n"
                        f"**Namespace**: {ptype_str}\n"
                        f"**Verification Status**: NOT_VERIFIED / OUT_OF_CORPUS\n"
                        f"**Requires Verification**: true"
                    )
                    return {
                        "answer": absence_answer,
                        "sources": [],
                        "query_type": "EXACT_PROVISION_QUERY",
                        "response_type": "EXACT_NOT_VERIFIED",
                        "temporal_status": "UNKNOWN",
                        "abstained": True,
                        "requires_verification": True,
                        "evidence_status": "OUT_OF_CORPUS",
                        "confidence_status": "REQUIRES_VERIFICATION",
                        "structured_query": resolved,
                        "qwen_invoked": False,
                        "adapter": None,
                        "retrieval_mode": "DETERMINISTIC_ABSENCE"
                    }
        else:
            # 7B-2. Check for multi-act cybercrime concept query
            if resolved.get("domain") == "CYBERCRIME":
                try:
                    from ..cybercrime.synthesizer import get_cybercrime_multi_act_response
                    cyber_resp = get_cybercrime_multi_act_response(self, question, resolved, top_k=top_k)
                    if cyber_resp:
                        return cyber_resp
                except Exception as e:
                    pass

            # 7C. Thematic or general inquiry: execute hybrid retrieval
            effective_search_q = f"{last_user_query} {question}" if is_context_followup else question
            filters = SearchFilter(
                state=state,
                court=court,
                incident_date=iso_date,
                act_prefix=resolved.get("act_prefix"),
                provision_number=None
            )
            retrieved_items = self.searcher.search(effective_search_q, filters=filters, top_k=top_k)

            # Secondary Retrieval Relevance Gate:
            # Reject candidates if they have no substantive legal overlap with the query
            if retrieved_items and not resolved.get("act_prefix"):
                q_tokens = set(re.findall(r'\b[a-zA-Z]{3,}\b', effective_search_q.lower()))
                stopwords = {
                    "what", "when", "where", "which", "who", "whom", "whose", "why", "how",
                    "does", "will", "would", "should", "could", "can", "are", "the", "and",
                    "for", "with", "about", "into", "through", "during", "before", "after",
                    "above", "below", "from", "under", "again", "further", "then", "once",
                    "here", "there", "all", "any", "both", "each", "few", "more", "most",
                    "other", "some", "such", "only", "own", "same", "than", "too", "very",
                    "just", "now", "tell", "give", "explain", "provide", "please", "able",
                    "things", "fro", "you", "doing"
                }
                substantive_q_tokens = q_tokens - stopwords

                filtered_candidates = []
                for chunk, score in retrieved_items:
                    chunk_text_lower = f"{chunk.title} {chunk.act_name} {chunk.section_or_article} {chunk.content[:400]}".lower()
                    overlap = [tok for tok in substantive_q_tokens if tok in chunk_text_lower]
                    if overlap:
                        filtered_candidates.append((chunk, score))

                if not filtered_candidates:
                    retrieved_items = []
                else:
                    retrieved_items = filtered_candidates

        # 8. General temporal criminal inquiry
        is_general_temporal_query = temp_eval is not None and not resolved.get("provision_number") and not resolved.get("act_prefix")
        if is_general_temporal_query:
            answer_text = (
                f"> [!NOTE]\n> **Applicable Temporal Framework**: {temp_eval['transition_note']}\n\n"
                f"### Temporal Legal Analysis (Article 20(1) Non-Retroactivity Framework)\n"
                f"Under Article 20(1) of the Constitution of India and Section 358 of the Bharatiya Nyaya Sanhita, 2023:\n"
                f"- **Substantive Law**: Governed by {temp_eval['applicable_substantive']}. Substantive criminal liability is strictly determined by the law in force at the time the act was committed.\n"
                f"- **Procedural Law**: Governed by {temp_eval['applicable_procedural']}.\n"
                f"- **Evidence Law**: Governed by {temp_eval['applicable_evidence']}."
            )
            return {
                "answer": answer_text,
                "sources": [
                    {
                        "chunk_id": chunk.chunk_id,
                        "title": chunk.title,
                        "citation": self.citation_engine.format_citation(chunk).citation_str,
                        "document_type": chunk.document_type.value,
                        "authority_tier": chunk.authority_tier.value,
                        "temporal_status": chunk.temporal_status.value,
                        "state": chunk.state,
                        "court": chunk.court,
                        "source_url": chunk.official_source_url,
                        "score": round(score, 4)
                    }
                    for chunk, score in retrieved_items[:2]
                ],
                "query_type": "GENERAL_LEGAL",
                "response_type": "GENERAL_LEGAL",
                "temporal_status": "VERIFIED_CURRENT",
                "abstained": False,
                "requires_verification": False,
                "evidence_status": "STATUTORY_AUTHORITY",
                "confidence_status": "TEMPORAL_TRANSITION_APPLIED",
                "structured_query": resolved,
                "qwen_invoked": False,
                "adapter": None,
                "retrieval_mode": "TEMPORAL_TRANSITION"
            }

        # 9. Safe Abstention if nothing retrieved
        if not retrieved_items:
            if struck_down_warning:
                return {
                    "answer": f"{struck_down_warning}\n\nNote: Further operational texts could not be verified from the current Indian legal corpus.",
                    "sources": [],
                    "query_type": "EXACT_PROVISION_QUERY" if is_exact_statutory_query else "GENERAL_LEGAL",
                    "response_type": "EXACT_NOT_VERIFIED" if is_exact_statutory_query else "GENERAL_LEGAL",
                    "temporal_status": "STRUCK_DOWN",
                    "abstained": False,
                    "requires_verification": True,
                    "evidence_status": "STATUTORY_AUTHORITY",
                    "confidence_status": "HIGH",
                    "structured_query": resolved,
                    "qwen_invoked": False,
                    "adapter": None,
                    "retrieval_mode": "STRUCK_DOWN_NOTICE"
                }
            if concordance_note:
                return {
                    "answer": f"{concordance_note}\n\nNote: Verbatim sections beyond this statutory transition could not be retrieved from the current Indian legal corpus.",
                    "sources": [],
                    "query_type": "GENERAL_LEGAL",
                    "response_type": "GENERAL_LEGAL",
                    "temporal_status": "CONCORDANCE_ONLY",
                    "abstained": False,
                    "requires_verification": True,
                    "evidence_status": "STATUTORY_AUTHORITY",
                    "confidence_status": "TEMPORAL_TRANSITION_APPLIED",
                    "structured_query": resolved,
                    "qwen_invoked": False,
                    "adapter": None,
                    "retrieval_mode": "CONCORDANCE_NOTICE"
                }

            if resolved.get("act_prefix") and resolved.get("provision_number"):
                act_title = resolved.get("act_title") or resolved.get("act_prefix")
                return {
                    "answer": f"Section {resolved['provision_number']} of {act_title} was not found in the available authoritative legal sources in the current corpus.",
                    "sources": [],
                    "query_type": "EXACT_PROVISION_QUERY",
                    "response_type": "EXACT_NOT_VERIFIED",
                    "temporal_status": "UNKNOWN",
                    "abstained": True,
                    "requires_verification": True,
                    "evidence_status": "INSUFFICIENT_RETRIEVAL",
                    "confidence_status": "INSUFFICIENT_RETRIEVAL",
                    "structured_query": resolved,
                    "qwen_invoked": False,
                    "adapter": None,
                    "retrieval_mode": "INSUFFICIENT_RETRIEVAL"
                }

            return {
                "answer": self.SAFE_ABSTENTION_MESSAGE,
                "sources": [],
                "query_type": "GENERAL_LEGAL",
                "response_type": "GENERAL_LEGAL",
                "temporal_status": "UNKNOWN",
                "abstained": True,
                "requires_verification": True,
                "evidence_status": "INSUFFICIENT_RETRIEVAL",
                "confidence_status": "INSUFFICIENT_RETRIEVAL",
                "structured_query": resolved,
                "qwen_invoked": False,
                "adapter": None,
                "retrieval_mode": "INSUFFICIENT_RETRIEVAL"
            }

        # 10. Qwen2.5-14B + LegalAI V2 Synthesis over verified evidence
        qwen_synthesis = None
        qwen_invoked = False
        adapter_used = None
        if self.base_pipeline:
            synthesis_question = (
                f"{last_user_query}\n\nClarification / Follow-up Request: {question}"
                if is_context_followup else question
            )
            qwen_synthesis = self.synthesize_legal_explanation(
                question=synthesis_question,
                retrieved_chunks=[c for c, _ in retrieved_items],
                query_type="EXACT_PROVISION_QUERY" if is_exact_statutory_query else "GENERAL_LEGAL",
                temporal_note=concordance_note or (temp_eval['transition_note'] if temp_eval else None)
            )
            if qwen_synthesis:
                qwen_invoked = True
                adapter_used = "outputs/qwen14b-legalai-v2"

        # Format answer and sources
        sources_list = []
        source_summaries = []
        has_struck_down_chunk = False

        for chunk, score in retrieved_items:
            if chunk.temporal_status == TemporalStatus.STRUCK_DOWN:
                has_struck_down_chunk = True
                if not struck_down_warning:
                    _, warn = self.temporal_validator.check_struck_down(chunk.act_prefix, chunk.provision_number)
                    struck_down_warning = warn

            cite = self.citation_engine.format_citation(chunk)
            provenance = self.citation_engine.format_lawyer_provenance_block(chunk)

            sources_list.append({
                "chunk_id": chunk.chunk_id,
                "title": chunk.title,
                "act_name": chunk.act_name,
                "act_prefix": chunk.act_prefix,
                "provision_number": chunk.provision_number,
                "provision_type": chunk.provision_type.value if hasattr(chunk.provision_type, 'value') else str(chunk.provision_type),
                "citation": cite.citation_str,
                "document_type": chunk.document_type.value,
                "authority_tier": chunk.authority_tier.value,
                "temporal_status": chunk.temporal_status.value,
                "state": chunk.state,
                "court": chunk.court,
                "source_url": chunk.official_source_url,
                "score": round(score, 4)
            })

            source_summaries.append(
                f"### {cite.citation_str}\n\n"
                f"{chunk.content}\n\n"
                f"{provenance}\n"
            )

        # Assemble full synthesis
        response_sections = []

        if struck_down_warning:
            response_sections.append(f"> [!WARNING]\n> **Judicial Invalidation Notice**:\n> {struck_down_warning}\n")

        if concordance_note:
            response_sections.append(f"> [!NOTE]\n> **Legal Transition Notice (1 July 2024)**:\n> {concordance_note}\n")

        if temp_eval:
            response_sections.append(f"> [!NOTE]\n> **Applicable Temporal Framework**: {temp_eval['transition_note']}\n")

        if qwen_synthesis:
            # Emit synthesis directly as primary top-level markdown
            response_sections.append(qwen_synthesis)

        if source_summaries:
            response_sections.append("\n---\n\n## Authoritative Indian Legal Authorities\n")
            response_sections.extend(source_summaries)

        final_answer = "\n".join(response_sections)
        final_temporal_status = "STRUCK_DOWN" if (struck_down_warning or has_struck_down_chunk) else "VERIFIED_CURRENT"

        confidence_status = "HIGH"
        if temp_eval:
            confidence_status = "TEMPORAL_TRANSITION_APPLIED"

        resp_type = "EXACT_VERIFIED" if is_exact_statutory_query else "GENERAL_LEGAL"

        return {
            "answer": final_answer,
            "sources": sources_list,
            "query_type": "EXACT_PROVISION_QUERY" if is_exact_statutory_query else "GENERAL_LEGAL",
            "response_type": resp_type,
            "temporal_status": final_temporal_status,
            "abstained": False,
            "requires_verification": (final_temporal_status == "STRUCK_DOWN"),
            "evidence_status": "STATUTORY_AUTHORITY",
            "confidence_status": confidence_status,
            "structured_query": resolved,
            "qwen_invoked": qwen_invoked,
            "adapter": adapter_used,
            "retrieval_mode": "EXACT_PROVISION" if is_exact_statutory_query else "HYBRID_BM25_VECTOR"
        }
