import React, { useState, useMemo } from 'react';
import { 
  X, 
  Sparkles, 
  Scale, 
  Calendar, 
  DollarSign, 
  ShieldAlert, 
  User, 
  Briefcase, 
  FileText,
  AlertTriangle,
  Zap,
  CheckCircle2,
  Clock
} from 'lucide-react';
import { Button } from '../common/Button';
import { Modal } from '../common/Modal';

export const AddCaseModal = ({ 
  isOpen, 
  onClose, 
  onCaseAdded 
}) => {
  const [activeTab, setActiveTab] = useState('essentials'); // essentials | court | stakes | timeline
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    title: '',
    client: '',
    clientPhone: '',
    opposingParty: '',
    opposingCounsel: '',
    court: 'High Court of Commercial Jurisdiction, Bench IV',
    caseType: 'Commercial Contracts & Maritime Liens',
    caseNumber: '',
    claimAmount: '₹15,00,00,000',
    claimValueNum: 150000000,
    reliefSought: '',
    isLibertyAtStake: false,
    status: 'Active',
    priority: 'urgent',
    nextHearing: '2026-10-05 10:30 AM',
    hearingCountdownDays: 6,
    description: '',
    tags: ['New Matter']
  });

  const [errors, setErrors] = useState({});

  // Auto-generate court-standard docket number
  const handleAutoGenerateDocket = () => {
    const year = 2026;
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    let prefix = 'CIVIL-SUIT';
    if (formData.caseType.includes('Commercial')) prefix = 'COMM-SUIT';
    else if (formData.caseType.includes('Criminal') || formData.isLibertyAtStake) prefix = 'CRL-BAIL';
    else if (formData.caseType.includes('Arbitration')) prefix = 'ARB-PET';
    else if (formData.caseType.includes('Probate')) prefix = 'TEST-CAS';
    
    setFormData(prev => ({
      ...prev,
      caseNumber: `${prefix}/${randomNum}/${year}`
    }));
  };

  // Live Multi-Factor Priority Calculation Preview
  const calculatedPriorityPreview = useMemo(() => {
    let proximityScore = 5;
    const days = parseInt(formData.hearingCountdownDays) || 999;
    if (days <= 2) proximityScore = 35;
    else if (days <= 5) proximityScore = 28;
    else if (days <= 8) proximityScore = 22;
    else if (days <= 15) proximityScore = 15;
    else if (days <= 30) proximityScore = 8;

    let financialScore = 5;
    const val = Number(formData.claimValueNum) || 0;
    if (val >= 100000000) financialScore = 25;
    else if (val >= 50000000) financialScore = 22;
    else if (val >= 10000000) financialScore = 18;
    else if (val >= 2500000) financialScore = 14;
    else if (val > 0) financialScore = 8;

    let libertyScore = 10;
    if (formData.isLibertyAtStake || formData.caseType.includes('Criminal')) {
      libertyScore = 25;
    } else if (formData.reliefSought.toLowerCase().includes('injunction') || formData.reliefSought.toLowerCase().includes('stay')) {
      libertyScore = 20;
    }

    let lawyerScore = 4;
    if (formData.priority === 'urgent' || formData.status === 'Urgent') lawyerScore = 14;
    else if (formData.status === 'Active') lawyerScore = 12;
    else if (formData.status === 'Upcoming') lawyerScore = 8;
    else if (formData.status === 'Pending') lawyerScore = 6;

    const totalScore = Math.min(100, proximityScore + financialScore + libertyScore + lawyerScore);
    const tier = totalScore >= 75 ? 'P1 - Critical' : totalScore >= 55 ? 'P2 - High' : totalScore >= 35 ? 'P3 - Medium' : 'P4 - Routine';

    return {
      totalScore,
      tier,
      proximityScore,
      financialScore,
      libertyScore,
      lawyerScore
    };
  }, [formData]);

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    if (type === 'checkbox') {
      setFormData(prev => ({ ...prev, [name]: checked }));
    } else if (name === 'claimAmount') {
      // Clean numeric value for computation
      const numeric = parseFloat(value.replace(/[^0-9.]/g, '')) || 0;
      setFormData(prev => ({ 
        ...prev, 
        claimAmount: value,
        claimValueNum: numeric
      }));
    } else {
      setFormData(prev => ({ ...prev, [name]: value }));
    }

    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: null }));
    }
  };

  const validate = () => {
    const errs = {};
    if (!formData.title.trim()) errs.title = 'Matter title is required';
    if (!formData.client.trim()) errs.client = 'Client name is required';
    if (!formData.court.trim()) errs.court = 'Court or forum is required';
    setErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validate()) return;

    setLoading(true);

    const payload = {
      ...formData,
      caseNumber: formData.caseNumber.trim() || `2026-CV-${Math.floor(1000 + Math.random() * 9000)}`,
      calculatedPriority: calculatedPriorityPreview.tier,
      priorityScore: calculatedPriorityPreview.totalScore,
      urgencyFactors: {
        proximityScore: calculatedPriorityPreview.proximityScore,
        financialScore: calculatedPriorityPreview.financialScore,
        libertyRiskScore: calculatedPriorityPreview.libertyScore,
        lawyerStatusScore: calculatedPriorityPreview.lawyerScore,
        totalScore: calculatedPriorityPreview.totalScore,
        tier: calculatedPriorityPreview.tier,
        hearingInDays: formData.hearingCountdownDays,
        claimFormatted: formData.claimAmount,
        keyReason: `Multi-factor priority intake: ${calculatedPriorityPreview.tier} (${calculatedPriorityPreview.totalScore}/100)`
      }
    };

    setTimeout(() => {
      setLoading(false);
      onCaseAdded(payload);
      onClose();
    }, 350);
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Intake New Legal Matter"
      subtitle="Register case into chambers docket with dynamic multi-factor priority intelligence"
      maxWidth="760px"
    >
      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
        
        {/* Top Priority Preview Banner */}
        <div style={{
          padding: '12px 16px',
          borderRadius: 'var(--radius-md)',
          backgroundColor: calculatedPriorityPreview.totalScore >= 75 
            ? 'rgba(239, 68, 68, 0.12)' 
            : calculatedPriorityPreview.totalScore >= 55 
              ? 'rgba(245, 158, 11, 0.12)' 
              : 'rgba(14, 165, 233, 0.12)',
          border: calculatedPriorityPreview.totalScore >= 75 
            ? '1px solid rgba(239, 68, 68, 0.3)' 
            : calculatedPriorityPreview.totalScore >= 55 
              ? '1px solid rgba(245, 158, 11, 0.3)' 
              : '1px solid rgba(14, 165, 233, 0.25)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '8px'
        }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Sparkles size={14} color={calculatedPriorityPreview.totalScore >= 75 ? '#EF4444' : '#F59E0B'} />
              <strong style={{ fontSize: '13px', color: 'var(--color-text-primary)' }}>
                Live Priority Assessment: {calculatedPriorityPreview.tier}
              </strong>
              <span style={{
                fontSize: '11px',
                fontWeight: 700,
                padding: '1px 6px',
                borderRadius: '8px',
                backgroundColor: 'var(--color-bg-surface)',
                color: calculatedPriorityPreview.totalScore >= 75 ? '#EF4444' : '#F59E0B'
              }}>
                {calculatedPriorityPreview.totalScore}/100 pts
              </span>
            </div>
            <p style={{ fontSize: '11.5px', color: 'var(--color-text-secondary)', margin: '2px 0 0 0' }}>
              Synthesized from: Proximity (+{calculatedPriorityPreview.proximityScore}), Financial Benefit (+{calculatedPriorityPreview.financialScore}), Liberty Risk (+{calculatedPriorityPreview.libertyScore}), Lawyer Flag (+{calculatedPriorityPreview.lawyerScore})
            </p>
          </div>
          
          <button
            type="button"
            onClick={handleAutoGenerateDocket}
            style={{
              padding: '5px 10px',
              borderRadius: '6px',
              backgroundColor: 'var(--color-bg-surface)',
              border: '1px solid var(--color-border-default)',
              fontSize: '11px',
              fontWeight: 600,
              color: 'var(--color-ink-900)',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '4px'
            }}
          >
            <Zap size={12} color="#0D9488" /> Generate Docket No.
          </button>
        </div>

        {/* Tab Navigation */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(4, 1fr)',
          gap: '4px',
          backgroundColor: 'var(--color-bg-surface-sunken)',
          padding: '4px',
          borderRadius: 'var(--radius-md)'
        }}>
          {[
            { id: 'essentials', label: '1. Essentials', icon: User },
            { id: 'court', label: '2. Forum & Docket', icon: Scale },
            { id: 'stakes', label: '3. Financial Stakes', icon: DollarSign },
            { id: 'timeline', label: '4. Strategy & Hearing', icon: Calendar }
          ].map(tab => {
            const Icon = tab.icon;
            const isCurrent = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                style={{
                  padding: '7px 8px',
                  borderRadius: 'var(--radius-sm)',
                  border: 'none',
                  backgroundColor: isCurrent ? 'var(--color-bg-surface)' : 'transparent',
                  color: isCurrent ? 'var(--color-ink-900)' : 'var(--color-text-secondary)',
                  fontWeight: isCurrent ? 650 : 500,
                  fontSize: '11.5px',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '5px',
                  boxShadow: isCurrent ? '0 1px 2px rgba(0,0,0,0.1)' : 'none',
                  transition: 'all 0.15s ease'
                }}
              >
                <Icon size={12} />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>

        {/* Tab 1: Matter Essentials */}
        {activeTab === 'essentials' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            <div>
              <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                Matter / Case Title <span style={{ color: 'var(--color-error-text)' }}>*</span>
              </label>
              <input
                type="text"
                name="title"
                value={formData.title}
                onChange={handleChange}
                placeholder="e.g. Tata Consultancy Services v. Horizon Data Networks Ltd."
                className="input-base"
                style={{ borderColor: errors.title ? 'var(--color-error-text)' : undefined }}
              />
              {errors.title && <span style={{ fontSize: '11px', color: 'var(--color-error-text)', marginTop: '2px', display: 'block' }}>{errors.title}</span>}
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-md)' }}>
              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Client Name <span style={{ color: 'var(--color-error-text)' }}>*</span>
                </label>
                <input
                  type="text"
                  name="client"
                  value={formData.client}
                  onChange={handleChange}
                  placeholder="e.g. Rajesh Khurana (Director)"
                  className="input-base"
                  style={{ borderColor: errors.client ? 'var(--color-error-text)' : undefined }}
                />
                {errors.client && <span style={{ fontSize: '11px', color: 'var(--color-error-text)', marginTop: '2px', display: 'block' }}>{errors.client}</span>}
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Client Contact / Email
                </label>
                <input
                  type="text"
                  name="clientPhone"
                  value={formData.clientPhone}
                  onChange={handleChange}
                  placeholder="+91 98100 45211 / legal@clientcorp.in"
                  className="input-base"
                />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-md)' }}>
              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Opposing Party
                </label>
                <input
                  type="text"
                  name="opposingParty"
                  value={formData.opposingParty}
                  onChange={handleChange}
                  placeholder="e.g. Horizon Data Networks & Ors."
                  className="input-base"
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Opposing Counsel / Firm
                </label>
                <input
                  type="text"
                  name="opposingCounsel"
                  value={formData.opposingCounsel}
                  onChange={handleChange}
                  placeholder="e.g. Adv. Vikramaditya Sen (Sen & Partners)"
                  className="input-base"
                />
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Court & Jurisdiction */}
        {activeTab === 'court' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-md)' }}>
              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Court / Tribunal Forum <span style={{ color: 'var(--color-error-text)' }}>*</span>
                </label>
                <input
                  type="text"
                  name="court"
                  value={formData.court}
                  onChange={handleChange}
                  placeholder="e.g. High Court Commercial Bench IV"
                  className="input-base"
                  style={{ borderColor: errors.court ? 'var(--color-error-text)' : undefined }}
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Docket / Case Number
                </label>
                <input
                  type="text"
                  name="caseNumber"
                  value={formData.caseNumber}
                  onChange={handleChange}
                  placeholder="e.g. COMM-SUIT/1187/2026"
                  className="input-base"
                  style={{ fontFamily: 'var(--font-mono)' }}
                />
              </div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                Practice Area / Case Classification
              </label>
              <select
                name="caseType"
                value={formData.caseType}
                onChange={handleChange}
                className="input-base"
              >
                <option>Commercial Contracts & Maritime Liens</option>
                <option>Substantive Criminal Law & Regular Bail (BNSS §480)</option>
                <option>Section 9 Arbitration & Commercial Enforcement</option>
                <option>Succession & Testamentary Trust Law</option>
                <option>Tort & Infrastructure Negligence Damages</option>
                <option>Insolvency & Bankruptcy (NCLT / IBC Code)</option>
                <option>Constitutional Writ & Public Law</option>
              </select>
            </div>
          </div>
        )}

        {/* Tab 3: Financial & Relief Stakes */}
        {activeTab === 'stakes' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            <div>
              <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                Disputed Claim Value / Financial Benefit (INR ₹)
              </label>
              <input
                type="text"
                name="claimAmount"
                value={formData.claimAmount}
                onChange={handleChange}
                placeholder="e.g. ₹18,50,00,000 (or ₹75 Lakhs)"
                className="input-base"
                style={{ fontWeight: 700 }}
              />
              <span style={{ fontSize: '11px', color: 'var(--color-text-muted)', marginTop: '2px', display: 'block' }}>
                High stakes (&gt; ₹10 Cr) dramatically enhance matter priority score in AI docket calculations.
              </span>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                Core Relief / Interim Injunction Prayer Sought
              </label>
              <textarea
                name="reliefSought"
                rows={2}
                value={formData.reliefSought}
                onChange={handleChange}
                placeholder="e.g. Ad-interim ex-parte injunction restraining respondent from invoking ₹6.4 Cr bank guarantee or alienating secured assets..."
                className="input-base"
                style={{ resize: 'vertical' }}
              />
            </div>

            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              padding: '10px 14px',
              borderRadius: 'var(--radius-md)',
              backgroundColor: 'var(--color-bg-surface-sunken)',
              border: '1px solid var(--color-border-subtle)'
            }}>
              <input
                type="checkbox"
                id="isLibertyAtStake"
                name="isLibertyAtStake"
                checked={formData.isLibertyAtStake}
                onChange={handleChange}
                style={{ width: '16px', height: '16px', cursor: 'pointer' }}
              />
              <label htmlFor="isLibertyAtStake" style={{ fontSize: '12px', fontWeight: 600, color: 'var(--color-text-primary)', cursor: 'pointer' }}>
                Personal Liberty / Arrest / Under-Trial Custody at Stake
                <span style={{ display: 'block', fontSize: '11px', fontWeight: 400, color: 'var(--color-text-muted)' }}>
                  Applies constitutional priority weighting (+25 pts) for urgent bail or anticipatory relief.
                </span>
              </label>
            </div>
          </div>
        )}

        {/* Tab 4: Strategy & Hearing */}
        {activeTab === 'timeline' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 0.8fr 1fr', gap: 'var(--space-md)' }}>
              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Next Hearing Date & Time
                </label>
                <input
                  type="text"
                  name="nextHearing"
                  value={formData.nextHearing}
                  onChange={handleChange}
                  placeholder="2026-10-05 10:30 AM"
                  className="input-base"
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Countdown (Days)
                </label>
                <input
                  type="number"
                  name="hearingCountdownDays"
                  value={formData.hearingCountdownDays}
                  onChange={handleChange}
                  className="input-base"
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                  Advocate Urgency
                </label>
                <select
                  name="priority"
                  value={formData.priority}
                  onChange={handleChange}
                  className="input-base"
                >
                  <option value="urgent">Urgent</option>
                  <option value="normal">Standard</option>
                </select>
              </div>
            </div>

            <div>
              <label style={{ display: 'block', fontSize: 'var(--text-label)', fontWeight: 600, color: 'var(--color-text-secondary)', marginBottom: '4px' }}>
                Matter Synopsis & Strategic Directives
              </label>
              <textarea
                name="description"
                rows={3}
                value={formData.description}
                onChange={handleChange}
                placeholder="Key substantive grounds, client instructions, and procedural steps for the cause list..."
                className="input-base"
                style={{ resize: 'vertical' }}
              />
            </div>
          </div>
        )}

        {/* Modal Actions */}
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginTop: 'var(--space-sm)',
          borderTop: '1px solid var(--color-border-subtle)',
          paddingTop: 'var(--space-md)'
        }}>
          <div style={{ display: 'flex', gap: '6px' }}>
            {activeTab !== 'essentials' && (
              <Button 
                variant="secondary" 
                size="sm" 
                onClick={() => {
                  if (activeTab === 'court') setActiveTab('essentials');
                  else if (activeTab === 'stakes') setActiveTab('court');
                  else if (activeTab === 'timeline') setActiveTab('stakes');
                }}
              >
                Previous Step
              </Button>
            )}
            {activeTab !== 'timeline' && (
              <Button 
                variant="secondary" 
                size="sm" 
                onClick={() => {
                  if (activeTab === 'essentials') setActiveTab('court');
                  else if (activeTab === 'court') setActiveTab('stakes');
                  else if (activeTab === 'stakes') setActiveTab('timeline');
                }}
              >
                Next Step
              </Button>
            )}
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <Button variant="secondary" onClick={onClose}>
              Cancel
            </Button>
            <Button variant="primary" type="submit" loading={loading}>
              Create & Prioritize Matter
            </Button>
          </div>
        </div>
      </form>
    </Modal>
  );
};
