"""
src/api/query_understanding/goals.py

Enumerations and schemas for Sub-Intents, User Goals, and Output Plans.
Decouples:
  Intent (Top-level taxonomy)
  ≠ Sub-Intent (Specific semantic nuance)
  ≠ User Goal (What the lawyer wants to achieve)
  ≠ Output Plan (Structured presentation schema)
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any


class SubIntent(str, Enum):
    # Case-specific sub-intents
    CASE_SUMMARY = "CASE_SUMMARY"
    CASE_KEY_POINTS = "CASE_KEY_POINTS"
    CASE_ISSUES = "CASE_ISSUES"
    CASE_FACTS = "CASE_FACTS"
    CASE_EVIDENCE = "CASE_EVIDENCE"
    CASE_EVIDENCE_GAPS = "CASE_EVIDENCE_GAPS"
    CASE_ARGUMENTS = "CASE_ARGUMENTS"
    CASE_COUNTERARGUMENTS = "CASE_COUNTERARGUMENTS"
    CASE_RISKS = "CASE_RISKS"
    CASE_TIMELINE = "CASE_TIMELINE"
    CASE_NEXT_STEPS = "CASE_NEXT_STEPS"
    CASE_DOCUMENT_ANALYSIS = "CASE_DOCUMENT_ANALYSIS"
    CASE_DRAFTING = "CASE_DRAFTING"
    CROSS_MATTER_COMPARISON = "CROSS_MATTER_COMPARISON"

    # Hearing sub-intents
    HEARING_PREPARATION = "HEARING_PREPARATION"
    HEARING_ARGUMENTS = "HEARING_ARGUMENTS"

    # Legal sub-intents
    EXACT_STATUTORY_PROVISION = "EXACT_STATUTORY_PROVISION"
    LEGAL_CONCEPT = "LEGAL_CONCEPT"
    LEGAL_PROCEDURE = "LEGAL_PROCEDURE"
    STATUTORY_PUNISHMENT = "STATUTORY_PUNISHMENT"

    # System & Technical sub-intents
    SYSTEM_SPECIFICATION = "SYSTEM_SPECIFICATION"
    TECHNICAL_CONCEPT = "TECHNICAL_CONCEPT"

    # Case Management sub-intents
    PORTFOLIO_WORKLOAD = "PORTFOLIO_WORKLOAD"
    PORTFOLIO_HEARINGS = "PORTFOLIO_HEARINGS"
    PORTFOLIO_DEADLINES = "PORTFOLIO_DEADLINES"
    CASE_PRIORITY = "CASE_PRIORITY"

    # Conversational & Boundary sub-intents
    GREETING = "GREETING"
    GRATITUDE = "GRATITUDE"
    ASSISTANT_IDENTITY = "ASSISTANT_IDENTITY"
    CONTEXT_FOLLOW_UP = "CONTEXT_FOLLOW_UP"
    NON_LEGAL_OUT_OF_SCOPE = "NON_LEGAL_OUT_OF_SCOPE"
    CLARIFICATION_REQUIRED = "CLARIFICATION_REQUIRED"


class UserGoal(str, Enum):
    UNDERSTAND_CASE = "UNDERSTAND_CASE"
    PRIORITIZE_CASE_ISSUES = "PRIORITIZE_CASE_ISSUES"
    PRIORITIZE_CASE = "PRIORITIZE_CASE"
    ANALYZE_EVIDENCE = "ANALYZE_EVIDENCE"
    IDENTIFY_EVIDENCE_GAPS = "IDENTIFY_EVIDENCE_GAPS"
    IDENTIFY_CASE_RISKS = "IDENTIFY_CASE_RISKS"
    ANALYZE_ARGUMENTS = "ANALYZE_ARGUMENTS"
    ANALYZE_COUNTERARGUMENTS = "ANALYZE_COUNTERARGUMENTS"
    HEARING_PREPARATION = "HEARING_PREPARATION"
    CHRONOLOGY_MAPPING = "CHRONOLOGY_MAPPING"
    RECOMMEND_NEXT_STEPS = "RECOMMEND_NEXT_STEPS"
    CASE_DRAFTING = "CASE_DRAFTING"
    RESEARCH_PROVISION = "RESEARCH_PROVISION"
    EXPLAIN_LEGAL_CONCEPT = "EXPLAIN_LEGAL_CONCEPT"
    PORTFOLIO_OVERVIEW = "PORTFOLIO_OVERVIEW"
    SYSTEM_ARCHITECTURE = "SYSTEM_ARCHITECTURE"
    TECHNICAL_EXPLANATION = "TECHNICAL_EXPLANATION"
    CONVERSATIONAL_EXCHANGE = "CONVERSATIONAL_EXCHANGE"
    IDENTIFY_ASSISTANT = "IDENTIFY_ASSISTANT"
    CLARIFY_QUERY = "CLARIFY_QUERY"
    REJECT_OUT_OF_SCOPE = "REJECT_OUT_OF_SCOPE"


class OutputPlan(str, Enum):
    KEY_POINTS = "KEY_POINTS"
    FOCUS_AREAS = "FOCUS_AREAS"
    CASE_SUMMARY = "CASE_SUMMARY"
    ESTABLISHED_FACTS = "ESTABLISHED_FACTS"
    KEY_ISSUES = "KEY_ISSUES"
    AVAILABLE_EVIDENCE = "AVAILABLE_EVIDENCE"
    EVIDENCE_GAPS = "EVIDENCE_GAPS"
    ARGUMENT_ANALYSIS = "ARGUMENT_ANALYSIS"
    POTENTIAL_ARGUMENTS = "POTENTIAL_ARGUMENTS"
    OPPOSING_ARGUMENTS = "OPPOSING_ARGUMENTS"
    CASE_RISKS = "CASE_RISKS"
    CHRONOLOGICAL_TIMELINE = "CHRONOLOGICAL_TIMELINE"
    ACTIONABLE_NEXT_STEPS = "ACTIONABLE_NEXT_STEPS"
    HEARING_BRIEF = "HEARING_BRIEF"
    CASE_PRIORITY_BRIEF = "CASE_PRIORITY_BRIEF"
    DRAFTING_WORKFLOW = "DRAFTING_WORKFLOW"
    DRAFTING_CLARIFICATION = "DRAFTING_CLARIFICATION"
    STATUTORY_ANALYSIS = "STATUTORY_ANALYSIS"
    CONCEPT_EXPLANATION = "CONCEPT_EXPLANATION"
    PORTFOLIO_TABLE = "PORTFOLIO_TABLE"
    SYSTEM_SPEC_SHEET = "SYSTEM_SPEC_SHEET"
    CONVERSATIONAL_RESPONSE = "CONVERSATIONAL_RESPONSE"
    ASSISTANT_IDENTITY = "ASSISTANT_IDENTITY"
    AMBIGUOUS_CLARIFICATION = "AMBIGUOUS_CLARIFICATION"
    OUT_OF_SCOPE_BOUNDARY = "OUT_OF_SCOPE_BOUNDARY"


@dataclass
class QueryUnderstandingResult:
    normalized_query: str
    original_query: str
    intent: str
    sub_intent: SubIntent
    user_goal: UserGoal
    output_plan: OutputPlan
    scope: str  # "CASE:<id>", "GENERAL", "PORTFOLIO", "SYSTEM"
    confidence: float
    reason: str
    target_case_id: Optional[str] = None
    target_document_type: Optional[str] = None
    length_preference: str = "balanced"  # "concise", "balanced", "comprehensive"
    protected_entities: Dict[str, Any] = field(default_factory=dict)
    clarification_prompt: Optional[str] = None
